### ISSUE TITLE
LogLevelDebug Logs are Printing to stderr

### ISSUE THREAD

**Issue by junger644** [bluenviron/goroslib#163]
## Which operating system are you using?

OS

- [X] Linux
- [ ] Windows
- [ ] macOS

Architecture

- [X] amd64
- [ ] arm64
- [ ] arm7
- [ ] arm6

## Describe the issue

LogLevelDebug logs are printing to stderr. See line 503 of node.go. I suggest they go to stdout as specified in Paragraph 2 of http://wiki.ros.org/roscpp/Overview/Logging.

**Comment by aler9** [comment]
Thanks for reporting the issue, it has been fixed.
