### ISSUE TITLE
Issue with IPv6 Address Parsing in Node Configuration

### ISSUE THREAD

**Issue by hesham1salem** [bluenviron/goroslib#195]
## Which operating system are you using?

OS

- [ x] Linux

Architecture

- [ x] amd64

## Describe the issue
I encountered an error when configuring a node in goroslib using an IPv6 address. Specifically, the application panics with the message when using the IPv6 address fc94:47d7:fc41:5099:e0cb:7560:2196:0647.
```bash
 "panic: listen tcp: address [IPv6 address]: too many colons in address" 
```
 Interestingly, altering afc94 with  4501  in the address  resolves the issue, suggesting a problem with parsing or handling the specific address.

```golang
package main

import (
	"github.com/bluenviron/goroslib/v2"
)

func main() {

	n, err := goroslib.NewNode(goroslib.NodeConf{
		Name: "goroslib_sub",
		//	MasterAddress: "[4501:47d7:fc41:5099:e0cb:7560:2196:0647]:11311",
		MasterAddress: "[fc94:47d7:fc41:5099:e0cb:7560:2196:0647]:11311",
	})
	if err != nil {
		panic(err)
	}
	defer n.Close()

}
```
the source of example 
https://github.com/bluenviron/goroslib/blob/ca98b523b42562e7c4abafb8a4d2615c296947b9/examples/subscriber-ipv6/main.go

**Comment by aler9** [comment]
Thanks for reporting the bug, this is fixed by #203

**Comment by hesham1salem** [comment]
thank you for fixing the bug 
I wish if you can update the release so we can get  the package direct with go get command instead of clone the repo
 inside my project
 @aler9

**Comment by aler9** [comment]
thanks for reminding me, i released the new version.
